### ISSUE TITLE
MVSEC Dataset for Semantic Segmentation

### ISSUE THREAD

**Issue by ldkong1205** [zexiJia/EvSegFormer#2]
Hi @zexiJia @hewh16, thanks for open-sourcing this work.

Regarding the mentioned experiments on the MVSEC dataset, where can I download the data and associated semantic labels? Thanks!

**Comment by CatherineCloud** [comment]
I have the same request. We would really appreciate it if the authors could kindly share the details to process MVSEC outdoor parts.

**Comment by ldkong1205** [comment]
Any updates? @zexiJia @hewh16

**Comment by zexiJia** [comment]
To process daytime Event data, you can follow the approach outlined in https://github.com/daniilidis-group/EV-FlowNet. This repository provides a comprehensive guide on handling Event data during daylight conditions, offering valuable insights and implementation details. Note that the segmentation labels require processing with a segmentation network based on grayscale images.
